import { beforeEach,describe,expect,it } from "vitest";
import postgres from "postgres";
import { PostgresPrimaryStore } from "@/adapters/postgres-primary-store/postgres-primary-store";
import { NodeIdentityAdapter } from "@/adapters/node-identity/node-identity";
import { FakeJudgeAdapter } from "@/adapters/fake-judge/fake-judge";
import { answer,finishReveal,lock,reveal,startOfficial } from "@/application/play/daily-game";

const url=process.env.DATABASE_URL;
const suite=url?describe:describe.skip;
const full="팀 경계가 소통 경계를 만들고 설계 결정이 그 경계를 따라 모여 시스템 구조가 조직 구조를 닮는다.";

suite("M2 PostgreSQL authority",()=>{
  let store:PostgresPrimaryStore;const identity=new NodeIdentityAdapter();const judge=new FakeJudgeAdapter();
  const deps=(instant="2026-09-08T14:59:59.000Z")=>({store,identity,judge,clock:{now:()=>new Date(instant)}});
  beforeEach(async()=>{const sql=postgres(url!);await sql`TRUNCATE daily_completions,guidance_events,node_discoveries,user_answers,play_sessions,anonymous_devices CASCADE`;await sql.end();store=new PostgresPrimaryStore(url!);});

  it("resolves the KST midnight boundary from server time",async()=>{expect((await store.resolveDaily(new Date("2026-09-08T14:59:59Z")))?.canonicalDate).toBe("2026-09-08");expect((await store.resolveDaily(new Date("2026-09-08T15:00:00Z")))?.canonicalDate).toBe("2026-09-09");});
  it("stores only a hash and resumes the same device",async()=>{const token=identity.randomToken();const hash=identity.hashToken(token);const made=await store.createDevice(hash);expect((await store.findActiveDevice(hash))?.id).toBe(made.id);const sql=postgres(url!);const [row]=await sql<{token_hash:string}[]>`SELECT token_hash FROM anonymous_devices WHERE id=${made.id}`;await sql.end();expect(row?.token_hash).toBe(hash);expect(row?.token_hash).not.toBe(token);});
  it("enforces one Official concurrently, while devices and Dailies remain independent",async()=>{const device=await store.createDevice(identity.hashToken(identity.randomToken()));const [a,b]=await Promise.all([startOfficial(deps(),device.id),startOfficial(deps(),device.id)]);expect(a!.session.id).toBe(b!.session.id);const tomorrow=await startOfficial(deps("2026-09-08T15:00:00Z"),device.id);expect(tomorrow!.session.id).not.toBe(a!.session.id);const other=await store.createDevice(identity.hashToken(identity.randomToken()));expect((await startOfficial(deps(),other.id))!.session.id).not.toBe(a!.session.id);});
  it("persists exact state across adapter instances and rejects foreign ownership",async()=>{const device=await store.createDevice(identity.hashToken(identity.randomToken()));const started=await startOfficial(deps(),device.id);await answer(deps(),device.id,started!.session.id,"팀 안에서 소통이 더 쉽고 팀 밖은 어렵다.");const restarted=new PostgresPrimaryStore(url!);const restored=await restarted.getOwnedSession(started!.session.id,device.id);expect(restored).toMatchObject({turnCount:1,stage:"REFLECT",contentVersionId:expect.any(String),thoughts:[{text:"팀 안에서 소통이 더 쉽고 팀 밖은 어렵다."}],guidance:[{key:"REFLECT"}]});const other=await restarted.createDevice(identity.hashToken(identity.randomToken()));expect(await restarted.getOwnedSession(started!.session.id,other.id)).toBeUndefined();await restarted.close();});
  it("keeps old Daily binding playable after midnight and completes Reveal exactly once",async()=>{const device=await store.createDevice(identity.hashToken(identity.randomToken()));const started=await startOfficial(deps(),device.id);await answer(deps("2026-09-08T15:00:00Z"),device.id,started!.session.id,full);await lock(deps(),device.id,started!.session.id);await finishReveal(deps(),device.id,started!.session.id);await finishReveal(deps(),device.id,started!.session.id);const sql=postgres(url!);const counts=await sql<{count:string}[]>`SELECT count(*) FROM daily_completions`;const [bound]=await sql<{daily_id:string;content_version_id:string}[]>`SELECT daily_id,content_version_id FROM play_sessions WHERE id=${started!.session.id}`;await sql.end();expect(counts[0]!.count).toBe("1");expect(bound).toMatchObject({daily_id:started!.daily.id,content_version_id:expect.any(String)});});
  it("uses state_version as a stale-write guard",async()=>{const device=await store.createDevice(identity.hashToken(identity.randomToken()));const started=await startOfficial(deps(),device.id);const session=await store.getOwnedSession(started!.session.id,device.id);expect(await store.saveTransition(session!.stateVersion,{...session!,stateVersion:session!.stateVersion+1})).toBe(true);expect(await store.saveTransition(session!.stateVersion,{...session!,stateVersion:session!.stateVersion+1})).toBe(false);});
  it("binds Reveal to the session version and makes approved rows immutable",async()=>{const device=await store.createDevice(identity.hashToken(identity.randomToken()));const started=await startOfficial(deps(),device.id);await answer(deps(),device.id,started!.session.id,full);await lock(deps(),device.id,started!.session.id);const sql=postgres(url!);const [v1]=await sql<{id:string;content_item_id:string}[]>`SELECT id,content_item_id FROM content_versions WHERE id=${(await store.getOwnedSession(started!.session.id,device.id))!.contentVersionId}`;const testVersion=100000+Math.floor(Math.random()*100000000);const testHash=identity.hashToken(identity.randomToken());const [v2]=await sql<{id:string}[]>`INSERT INTO content_versions(content_item_id,version,schema_version,content_hash,status,public_play,judge_rubric,server_policy,reveal_content,approved_at) SELECT content_item_id,${testVersion},schema_version,${testHash},status,public_play,judge_rubric,server_policy,jsonb_set(reveal_content,'{theory}','"Future Secret"'),approved_at FROM content_versions WHERE id=${v1!.id} RETURNING id`;await sql`UPDATE daily_schedule SET content_version_id=${v2!.id} WHERE id=${started!.daily.id}`;expect((await reveal(deps(),device.id,started!.session.id))!.theory).toBe("Conway's Law");await expect(sql`UPDATE content_versions SET content_hash=${identity.hashToken(identity.randomToken())} WHERE id=${v1!.id}`).rejects.toThrow(/immutable/);await sql`UPDATE daily_schedule SET content_version_id=${v1!.id} WHERE id=${started!.daily.id}`;await sql.end();});
});
