import { beforeEach,describe,expect,it } from "vitest";
import postgres from "postgres";
import { PostgresPrimaryStore } from "@/adapters/postgres-primary-store/postgres-primary-store";
import { NodeIdentityAdapter } from "@/adapters/node-identity/node-identity";
import { FakeJudgeAdapter } from "@/adapters/fake-judge/fake-judge";
import { answer,finishReveal,lock,reveal,startOfficial } from "@/application/play/daily-game";
import rawContent from "../../content/approved/conway-law.v1.json";
import rawSchedule from "../../content/schedule/daily.v1.json";
import { approvedContentSchema,dailyScheduleSchema } from "@/domain/content/schema";
import { contentVersionHash,seedApprovedData } from "../../tooling/content-tools.mts";
import { OpenAIJudgeAdapter,type OpenAIJudgeTransport,type OpenAIJudgeTransportRequest } from "@/adapters/openai-judge/openai-judge";
import { JudgeExecutionError } from "@/ports/judge";

const url=process.env.DATABASE_URL;
const suite=url?describe:describe.skip;
const full="팀 경계가 소통 경계를 만들고 설계 결정이 그 경계를 따라 모여 시스템 구조가 조직 구조를 닮는다.";
const approved=approvedContentSchema.parse(rawContent);const approvedSchedule=dailyScheduleSchema.parse(rawSchedule);
const providerVerdict=(text:string)=>({answerType:"REASONING",ambiguity:"NONE",nodes:approved.JUDGE_RUBRIC.nodes.map(n=>({nodeId:n.id,status:"DISCOVERED",evidenceText:text}))});
class ScriptedProvider implements OpenAIJudgeTransport{readonly requests:OpenAIJudgeTransportRequest[]=[];constructor(private readonly script:unknown[]){}async classify(request:OpenAIJudgeTransportRequest){this.requests.push(request);const value=this.script.shift();if(value instanceof Error)throw value;return{output:value,inputTokens:8,outputTokens:4,totalTokens:12,providerRequestId:`req-${this.requests.length}`};}}

suite("M2 PostgreSQL authority",()=>{
  let store:PostgresPrimaryStore;const identity=new NodeIdentityAdapter();const judge=new FakeJudgeAdapter();
  const deps=(instant="2026-09-08T14:59:59.000Z")=>({store,identity,judge,clock:{now:()=>new Date(instant)}});
  beforeEach(async()=>{const sql=postgres(url!);await sql`TRUNCATE ai_runs,daily_completions,guidance_events,node_discoveries,user_answers,play_sessions,anonymous_devices CASCADE`;await sql`DELETE FROM daily_schedule WHERE canonical_date>'2026-09-09'`;await sql.end();store=new PostgresPrimaryStore(url!);});

  it("resolves the KST midnight boundary and returns no unscheduled date",async()=>{expect((await store.resolveDaily(new Date("2026-09-08T14:59:59Z")))?.canonicalDate).toBe("2026-09-08");expect((await store.resolveDaily(new Date("2026-09-08T15:00:00Z")))?.canonicalDate).toBe("2026-09-09");expect(await store.resolveDaily(new Date("2026-09-09T15:00:00Z"))).toBeUndefined();});
  it("stores only a hash and resumes the same device",async()=>{const token=identity.randomToken();const hash=identity.hashToken(token);const made=await store.createDevice(hash);expect((await store.findActiveDevice(hash))?.id).toBe(made.id);const sql=postgres(url!);const [row]=await sql<{token_hash:string}[]>`SELECT token_hash FROM anonymous_devices WHERE id=${made.id}`;await sql.end();expect(row?.token_hash).toBe(hash);expect(row?.token_hash).not.toBe(token);});
  it("enforces one Official concurrently, while devices and Dailies remain independent",async()=>{const device=await store.createDevice(identity.hashToken(identity.randomToken()));const [a,b]=await Promise.all([startOfficial(deps(),device.id),startOfficial(deps(),device.id)]);expect(a!.session.id).toBe(b!.session.id);const tomorrow=await startOfficial(deps("2026-09-08T15:00:00Z"),device.id);expect(tomorrow!.session.id).not.toBe(a!.session.id);const other=await store.createDevice(identity.hashToken(identity.randomToken()));expect((await startOfficial(deps(),other.id))!.session.id).not.toBe(a!.session.id);});
  it("persists exact state across adapter instances and rejects foreign ownership",async()=>{const device=await store.createDevice(identity.hashToken(identity.randomToken()));const started=await startOfficial(deps(),device.id);await answer(deps(),device.id,started!.session.id,"팀 안에서 소통이 더 쉽고 팀 밖은 어렵다.");const restarted=new PostgresPrimaryStore(url!);const restored=await restarted.getOwnedSession(started!.session.id,device.id);expect(restored).toMatchObject({turnCount:1,stage:"REFLECT",contentVersionId:expect.any(String),thoughts:[{text:"팀 안에서 소통이 더 쉽고 팀 밖은 어렵다."}],guidance:[{key:"REFLECT"}]});const other=await restarted.createDevice(identity.hashToken(identity.randomToken()));expect(await restarted.getOwnedSession(started!.session.id,other.id)).toBeUndefined();await restarted.close();});
  it("keeps old Daily binding playable on an unscheduled later date and completes Reveal exactly once",async()=>{const device=await store.createDevice(identity.hashToken(identity.randomToken()));const started=await startOfficial(deps(),device.id);await answer(deps("2026-09-09T15:00:00Z"),device.id,started!.session.id,full);await lock(deps(),device.id,started!.session.id);await finishReveal(deps(),device.id,started!.session.id);await finishReveal(deps(),device.id,started!.session.id);const sql=postgres(url!);const counts=await sql<{count:string}[]>`SELECT count(*) FROM daily_completions`;const [bound]=await sql<{daily_id:string;content_version_id:string}[]>`SELECT daily_id,content_version_id FROM play_sessions WHERE id=${started!.session.id}`;await sql.end();expect(counts[0]!.count).toBe("1");expect(bound).toMatchObject({daily_id:started!.daily.id,content_version_id:expect.any(String)});});
  it("uses state_version as a stale-write guard",async()=>{const device=await store.createDevice(identity.hashToken(identity.randomToken()));const started=await startOfficial(deps(),device.id);const session=await store.getOwnedSession(started!.session.id,device.id);expect(await store.saveTransition(session!.stateVersion,{...session!,stateVersion:session!.stateVersion+1})).toBe(true);expect(await store.saveTransition(session!.stateVersion,{...session!,stateVersion:session!.stateVersion+1})).toBe(false);});
  it("persists non-BMP text exactly with PostgreSQL character count",async()=>{const text="😀 팀 안 소통은 쉽다.";const device=await store.createDevice(identity.hashToken(identity.randomToken()));const started=await startOfficial(deps(),device.id);await answer(deps(),device.id,started!.session.id,text);const restarted=new PostgresPrimaryStore(url!);expect((await restarted.getOwnedSession(started!.session.id,device.id))!.thoughts[0]!.text).toBe(text);const sql=postgres(url!);const [row]=await sql<{text:string;char_count:number}[]>`SELECT text,char_count FROM user_answers WHERE session_id=${started!.session.id}`;await sql.end();expect(row).toEqual({text,char_count:Array.from(text).length});await restarted.close();});
  it("binds Reveal to the session version and makes approved rows immutable",async()=>{const device=await store.createDevice(identity.hashToken(identity.randomToken()));const started=await startOfficial(deps(),device.id);await answer(deps(),device.id,started!.session.id,full);await lock(deps(),device.id,started!.session.id);const sql=postgres(url!);const [v1]=await sql<{id:string;content_item_id:string}[]>`SELECT id,content_item_id FROM content_versions WHERE id=${(await store.getOwnedSession(started!.session.id,device.id))!.contentVersionId}`;const testVersion=100000+Math.floor(Math.random()*100000000);const testHash=identity.hashToken(identity.randomToken());await sql`INSERT INTO content_versions(content_item_id,version,schema_version,content_hash,status,public_play,judge_rubric,server_policy,reveal_content,approved_at) SELECT content_item_id,${testVersion},schema_version,${testHash},status,public_play,judge_rubric,server_policy,jsonb_set(reveal_content,'{theory}','"Future Secret"'),approved_at FROM content_versions WHERE id=${v1!.id}`;expect((await reveal(deps(),device.id,started!.session.id))!.theory).toBe("Conway's Law");await expect(sql`UPDATE content_versions SET content_hash=${identity.hashToken(identity.randomToken())} WHERE id=${v1!.id}`).rejects.toThrow(/immutable/);await sql.end();});
  it("accepts exact seed reruns and schedule-only extension without changing content hash",async()=>{await seedApprovedData(url!,[{file:"conway",content:approved}],[{file:"daily",schedule:approvedSchedule}]);const before=contentVersionHash(approved);const extension=dailyScheduleSchema.parse({schema_version:1,entries:[{canonical_date:"2026-09-10",sequence_number:3,release_at:"2026-09-09T15:00:00.000Z",content:{slug:"conway-law",version:1}}]});await seedApprovedData(url!,[{file:"conway",content:approved}],[{file:"extension",schedule:extension}]);const sql=postgres(url!);const [row]=await sql<{content_hash:string}[]>`SELECT content_hash FROM content_versions v JOIN content_items i ON i.id=v.content_item_id WHERE i.slug='conway-law' AND v.version=1`;await sql.end();expect(row!.content_hash).toBe(before);});
  it("rejects incompatible same-date schedules and sequence collisions",async()=>{const incompatible=dailyScheduleSchema.parse({schema_version:1,entries:[{canonical_date:"2026-09-08",sequence_number:99,release_at:"2026-09-07T15:00:00.000Z",content:{slug:"conway-law",version:1}}]});await expect(seedApprovedData(url!,[],[{file:"conflict",schedule:incompatible}])).rejects.toThrow(/incompatible schedule/);const collision=dailyScheduleSchema.parse({schema_version:1,entries:[{canonical_date:"2026-09-10",sequence_number:1,release_at:"2026-09-09T15:00:00.000Z",content:{slug:"conway-law",version:1}}]});await expect(seedApprovedData(url!,[],[{file:"collision",schedule:collision}])).rejects.toThrow(/sequence 1 already assigned/);});
  it("rejects four-layer mutation under the same approved version",async()=>{const changed=structuredClone(approved);changed.PUBLIC_PLAY.scenario+=" 변경";await expect(seedApprovedData(url!,[{file:"changed",content:changed}],[])).rejects.toThrow(/create a new version/);});
  it("reserves EVALUATING outside the provider wait and persists a successful mocked Judge result",async()=>{const text=full;const provider=new ScriptedProvider([providerVerdict(text)]);const realJudge=new OpenAIJudgeAdapter(provider,"candidate-model",()=>0);const device=await store.createDevice(identity.hashToken(identity.randomToken()));const started=await startOfficial(deps(),device.id);const during=provider.classify.bind(provider);provider.classify=async request=>{const current=await store.getOwnedSession(started!.session.id,device.id);expect(current).toMatchObject({status:"EVALUATING",turnCount:1,thoughts:[{text}]});return during(request);};const result=await answer({...deps(),judge:realJudge},device.id,started!.session.id,text);expect(result!.outcome).toBe("LOCKABLE");const restored=await store.getOwnedSession(started!.session.id,device.id);expect(restored).toMatchObject({status:"LOCKABLE",stateVersion:2});});
  it("retries one provider failure and records both redacted attempts",async()=>{const provider=new ScriptedProvider([new Error("raw provider secret"),providerVerdict(full)]);const device=await store.createDevice(identity.hashToken(identity.randomToken()));const started=await startOfficial(deps(),device.id);await answer({...deps(),judge:new OpenAIJudgeAdapter(provider,"candidate-model",()=>0)},device.id,started!.session.id,full);const sql=postgres(url!);const rows=await sql<{attempt:number;result_status:string;model:string;payload:string}[]>`SELECT attempt,result_status,model,to_jsonb(ai_runs)::text payload FROM ai_runs ORDER BY attempt`;await sql.end();expect(rows.map(({attempt,result_status,model})=>({attempt,result_status,model}))).toEqual([{attempt:1,result_status:"PROVIDER_ERROR",model:"candidate-model"},{attempt:2,result_status:"SUCCEEDED",model:"candidate-model"}]);expect(JSON.stringify(rows)).not.toContain(full);expect(JSON.stringify(rows)).not.toContain("raw provider secret");});
  it("recovers after two provider failures without consuming the answer or leaking raw text",async()=>{const provider=new ScriptedProvider([new Error("raw one"),new Error("raw two")]);const device=await store.createDevice(identity.hashToken(identity.randomToken()));const started=await startOfficial(deps(),device.id);await expect(answer({...deps(),judge:new OpenAIJudgeAdapter(provider,"candidate-model",()=>0)},device.id,started!.session.id,"민감한 원문 생각")).rejects.toBeInstanceOf(JudgeExecutionError);expect(await store.getOwnedSession(started!.session.id,device.id)).toMatchObject({status:"THINKING",turnCount:0,thoughts:[],stateVersion:2});const retry=await answer({...deps(),judge:new OpenAIJudgeAdapter(new ScriptedProvider([providerVerdict(full)]),"candidate-model",()=>0)},device.id,started!.session.id,full);expect(retry?.outcome).toBe("LOCKABLE");expect((await store.getOwnedSession(started!.session.id,device.id))?.stateVersion).toBe(4);const sql=postgres(url!);const runs=await sql<{answer_id:string|null;payload:string}[]>`SELECT answer_id,to_jsonb(ai_runs)::text payload FROM ai_runs`;await sql.end();expect(runs).toHaveLength(3);expect(runs.filter(r=>r.answer_id===null)).toHaveLength(2);expect(JSON.stringify(runs)).not.toContain("민감한 원문 생각");expect(JSON.stringify(runs)).not.toContain("raw one");expect(JSON.stringify(runs)).not.toContain(full);});
  it("rejects invalid literal evidence, stores only its redacted category, and leaves node state untouched",async()=>{const bad={...providerVerdict(full),nodes:providerVerdict(full).nodes.map((n,i)=>i===0?{...n,evidenceText:"fabricated"}:n)};const provider=new ScriptedProvider([bad,bad]);const device=await store.createDevice(identity.hashToken(identity.randomToken()));const started=await startOfficial(deps(),device.id);await expect(answer({...deps(),judge:new OpenAIJudgeAdapter(provider,"candidate-model",()=>0)},device.id,started!.session.id,full)).rejects.toBeInstanceOf(JudgeExecutionError);const restored=await store.getOwnedSession(started!.session.id,device.id);expect(restored!.discoveries.every(n=>n.status==="ABSENT")).toBe(true);expect(restored).toMatchObject({status:"THINKING",turnCount:0});const sql=postgres(url!);const rows=await sql<{failure_category:string;payload:string}[]>`SELECT failure_category,to_jsonb(ai_runs)::text payload FROM ai_runs ORDER BY attempt`;await sql.end();expect(rows.map(row=>row.failure_category)).toEqual(["EVIDENCE_NOT_LITERAL","EVIDENCE_NOT_LITERAL"]);expect(JSON.stringify(rows)).not.toContain(full);expect(JSON.stringify(rows)).not.toContain("fabricated");});
  it("rejects cross-session evidence, mismatched completion Daily, and invalid session binding",async()=>{
    const deviceA=await store.createDevice(identity.hashToken(identity.randomToken()));const deviceB=await store.createDevice(identity.hashToken(identity.randomToken()));const a=await startOfficial(deps(),deviceA.id);const b=await startOfficial(deps(),deviceB.id);await answer(deps(),deviceA.id,a!.session.id,full);await answer(deps(),deviceB.id,b!.session.id,full);
    const sql=postgres(url!);const [answerA]=await sql<{id:string}[]>`SELECT id FROM user_answers WHERE session_id=${a!.session.id}`;
    await expect(sql`UPDATE play_sessions SET lock_answer_id=${answerA!.id},lock_span_start=0,lock_span_end=1 WHERE id=${b!.session.id}`).rejects.toThrow(/play_sessions_lock_answer_ownership_fk/);
    await expect(sql`UPDATE node_discoveries SET first_answer_id=${answerA!.id},evidence_span_start=0,evidence_span_end=1 WHERE session_id=${b!.session.id} AND node_id='TEAM_BOUNDARIES'`).rejects.toThrow(/node_discoveries_evidence_ownership_fk/);
    await expect(sql`UPDATE node_discoveries SET contradiction_answer_id=${answerA!.id},contradiction_span_start=0,contradiction_span_end=1 WHERE session_id=${b!.session.id} AND node_id='SYSTEM_RESEMBLANCE'`).rejects.toThrow(/node_discoveries_contradiction_ownership_fk/);
    const [tomorrow]=await sql<{id:string}[]>`SELECT id FROM daily_schedule WHERE canonical_date='2026-09-09'`;
    await expect(sql`INSERT INTO daily_completions(session_id,daily_id) VALUES(${a!.session.id},${tomorrow!.id})`).rejects.toThrow(/daily_completions_session_daily_fk/);
    const boundContent=(await store.getOwnedSession(a!.session.id,deviceA.id))!.contentVersionId;const testVersion=200000+Math.floor(Math.random()*100000000);const [otherVersion]=await sql<{id:string}[]>`INSERT INTO content_versions(content_item_id,version,schema_version,content_hash,status,public_play,judge_rubric,server_policy,reveal_content,approved_at) SELECT content_item_id,${testVersion},schema_version,${identity.hashToken(identity.randomToken())},status,public_play,judge_rubric,server_policy,reveal_content,approved_at FROM content_versions WHERE id=${boundContent} RETURNING id`;
    await expect(sql`INSERT INTO play_sessions(daily_id,content_version_id,anonymous_device_id,attempt_type,status,stage) VALUES(${a!.daily.id},${otherVersion!.id},${deviceA.id},'PRACTICE','THINKING','BLIND')`).rejects.toThrow(/play_sessions_daily_content_binding_fk/);
    await expect(sql`UPDATE play_sessions SET daily_id=${tomorrow!.id} WHERE id=${a!.session.id}`).rejects.toThrow(/binding is immutable/);await sql.end();
  });
});
