import OpenAI,{APIConnectionError,APIError} from "openai";
import { zodTextFormat } from "openai/helpers/zod";
import { z } from "zod";
import { FINAL_SYNTHESIS_V2_COMPONENT_MATCHES,FINAL_SYNTHESIS_V2_ENDORSEMENT_STATUSES,FINAL_SYNTHESIS_V2_REFERENCE_STATUSES,FinalSynthesisV2ExecutionError,FinalSynthesisV2ProofValidationError,validateFinalSynthesisV2ProofStructure,type FinalSynthesisV2AttemptFailureCategory,type FinalSynthesisVerifierV2Attempt,type FinalSynthesisVerifierV2Input,type FinalSynthesisVerifierV2Port,type UnvalidatedFinalSynthesisV2Proof } from "@/ports/final-synthesis-verifier-v2";
import { FINAL_SYNTHESIS_V2_PROMPT_VERSION,FINAL_SYNTHESIS_V2_SYSTEM_PROMPT } from "@/shared/final-synthesis-verifier-v2-prompt";

export interface FinalSynthesisV2ProofContract{readonly nodeId:string;readonly componentIds:readonly string[]}
export function buildFinalSynthesisV2ProviderSchema(contract:readonly FinalSynthesisV2ProofContract[],unitIds:readonly string[]){if(!contract.length||!unitIds.length)throw new Error("FINAL_SYNTHESIS_V2_PROVIDER_CONTRACT_EMPTY");const nodeIds=contract.map(x=>x.nodeId) as [string,...string[]],componentIds=[...new Set(contract.flatMap(x=>x.componentIds))] as [string,...string[]];if(!componentIds.length)throw new Error("FINAL_SYNTHESIS_V2_PROVIDER_CONTRACT_EMPTY");const component=z.object({componentId:z.enum(componentIds),endorsementStatus:z.enum(FINAL_SYNTHESIS_V2_ENDORSEMENT_STATUSES),referenceStatus:z.enum(FINAL_SYNTHESIS_V2_REFERENCE_STATUSES),componentMatch:z.enum(FINAL_SYNTHESIS_V2_COMPONENT_MATCHES),evidenceUnitIds:z.array(z.enum(unitIds as [string,...string[]])).max(unitIds.length),antecedentEvidenceUnitIds:z.array(z.enum(unitIds as [string,...string[]])).max(unitIds.length)}).strict();const node=z.object({nodeId:z.enum(nodeIds),components:z.array(component).min(1).max(componentIds.length)}).strict();return z.object({nodes:z.array(node).length(nodeIds.length)}).strict()}
export interface OpenAIFinalSynthesisV2TransportRequest{readonly model:string;readonly promptVersion:typeof FINAL_SYNTHESIS_V2_PROMPT_VERSION;readonly systemPrompt:string;readonly input:string;readonly contract:readonly FinalSynthesisV2ProofContract[];readonly evidenceUnitIds:readonly string[]}
export interface OpenAIFinalSynthesisV2TransportResult{readonly output:unknown;readonly inputTokens?:number;readonly outputTokens?:number;readonly totalTokens?:number;readonly providerRequestId?:string}
export interface OpenAIFinalSynthesisV2Transport{extract(request:OpenAIFinalSynthesisV2TransportRequest):Promise<OpenAIFinalSynthesisV2TransportResult>}
export interface FinalSynthesisV2TransportExecutionObserver{recordTransportExecution():void}
export type OpenAIFinalSynthesisV2RequestInvoker=(request:ReturnType<typeof buildOpenAIFinalSynthesisV2ResponseRequest>)=>Promise<OpenAIFinalSynthesisV2TransportResult>;
export function buildOpenAIFinalSynthesisV2ClientOptions(apiKey:string):ConstructorParameters<typeof OpenAI>[0]{return{apiKey,maxRetries:0,logLevel:"off"}}
export function buildOpenAIFinalSynthesisV2ResponseRequest(request:OpenAIFinalSynthesisV2TransportRequest){return{model:request.model,instructions:request.systemPrompt,input:request.input,text:{format:zodTextFormat(buildFinalSynthesisV2ProviderSchema(request.contract,request.evidenceUnitIds),"g1_final_synthesis_v2")},store:false as const,tools:[],tool_choice:"none" as const}}
export function serializeFinalSynthesisV2SemanticInput(input:FinalSynthesisVerifierV2Input){return JSON.stringify({requiredNodes:input.requiredNodes,submission:input.submission,evidenceUnits:input.evidenceUnits})}
class FinalSynthesisV2LocalRequestBuildError extends Error{constructor(readonly original:unknown){super("FINAL_SYNTHESIS_V2_LOCAL_REQUEST_BUILD_FAILED")}}
class FinalSynthesisV2ProviderInvocationError extends Error{constructor(readonly original:unknown){super("FINAL_SYNTHESIS_V2_PROVIDER_INVOCATION_FAILED")}}
export class OpenAIResponsesFinalSynthesisV2Transport implements OpenAIFinalSynthesisV2Transport{private readonly invoke:OpenAIFinalSynthesisV2RequestInvoker;constructor(apiKey:string,private readonly executionObserver:FinalSynthesisV2TransportExecutionObserver,invoke?:OpenAIFinalSynthesisV2RequestInvoker){this.invoke=invoke??createInvoker(apiKey)}async extract(request:OpenAIFinalSynthesisV2TransportRequest):Promise<OpenAIFinalSynthesisV2TransportResult>{let built:ReturnType<typeof buildOpenAIFinalSynthesisV2ResponseRequest>;try{built=buildOpenAIFinalSynthesisV2ResponseRequest(request)}catch(error){throw new FinalSynthesisV2LocalRequestBuildError(error)}this.executionObserver.recordTransportExecution();try{return await this.invoke(built)}catch(error){throw new FinalSynthesisV2ProviderInvocationError(error)}}}
function createInvoker(apiKey:string):OpenAIFinalSynthesisV2RequestInvoker{const client=new OpenAI(buildOpenAIFinalSynthesisV2ClientOptions(apiKey));return async request=>{const result=await client.responses.parse(request).withResponse();if(!result.data.output_parsed)throw new Error("SCHEMA_INVALID");const usage=result.data.usage;return{output:result.data.output_parsed,...(usage?{inputTokens:usage.input_tokens,outputTokens:usage.output_tokens,totalTokens:usage.total_tokens}:{}),...(result.request_id?{providerRequestId:result.request_id}:{})}}}
export class OpenAIFinalSynthesisVerifierV2Adapter implements FinalSynthesisVerifierV2Port{readonly promptVersion=FINAL_SYNTHESIS_V2_PROMPT_VERSION;constructor(private readonly transport:OpenAIFinalSynthesisV2Transport,private readonly model:string,private readonly nowMs:()=>number=()=>performance.now()){}async extractProof(input:FinalSynthesisVerifierV2Input){const attempts:FinalSynthesisVerifierV2Attempt[]=[];const request:OpenAIFinalSynthesisV2TransportRequest={model:this.model,promptVersion:this.promptVersion,systemPrompt:FINAL_SYNTHESIS_V2_SYSTEM_PROMPT,input:serializeFinalSynthesisV2SemanticInput(input),contract:input.requiredNodes.map(node=>({nodeId:node.nodeId,componentIds:node.requiredComponents.map(component=>component.componentId)})),evidenceUnitIds:input.evidenceUnits.map(unit=>unit.unitId)};for(let attempt=1;attempt<=2;attempt++){const started=this.nowMs();let response:OpenAIFinalSynthesisV2TransportResult|undefined;try{response=await this.transport.extract(request);const parsed=buildFinalSynthesisV2ProviderSchema(request.contract,request.evidenceUnitIds).parse(response.output) as UnvalidatedFinalSynthesisV2Proof;validateFinalSynthesisV2ProofStructure(parsed,input);attempts.push(meta(attempt,this.model,Math.max(0,Math.round(this.nowMs()-started)),"SUCCEEDED",true,true,response));return{proof:parsed,attempts}}catch(error){const failure=classify(error,response!==undefined);attempts.push(meta(attempt,this.model,Math.max(0,Math.round(this.nowMs()-started)),failure.resultStatus,failure.schemaValid,failure.providerRequestStarted,response,failure.category,failure.reason,failure.diagnostic))}}throw new FinalSynthesisV2ExecutionError(attempts)}}
interface SafeFailureDiagnostic{readonly errorClass?:string;readonly errorCode?:string;readonly httpStatus?:number;readonly providerRequestId?:string;readonly retryAfter?:string;readonly errorMessage?:string}
function meta(attempt:number,model:string,latencyMs:number,resultStatus:FinalSynthesisVerifierV2Attempt["resultStatus"],schemaValid:boolean,providerRequestStarted:boolean,response?:OpenAIFinalSynthesisV2TransportResult,failureCategory?:FinalSynthesisV2AttemptFailureCategory,validationReason?:FinalSynthesisVerifierV2Attempt["validationReason"],diagnostic:SafeFailureDiagnostic={}):FinalSynthesisVerifierV2Attempt{return{attempt,provider:"openai",model,promptVersion:FINAL_SYNTHESIS_V2_PROMPT_VERSION,schemaValid,resultStatus,providerRequestStarted,latencyMs,...(failureCategory?{failureCategory}:{}),...(validationReason?{validationReason}:{}),...(response?.inputTokens!==undefined?{inputTokens:response.inputTokens}:{}),...(response?.outputTokens!==undefined?{outputTokens:response.outputTokens}:{}),...(response?.totalTokens!==undefined?{totalTokens:response.totalTokens}:{}),...(response?.providerRequestId?{providerRequestId:response.providerRequestId}:diagnostic.providerRequestId?{providerRequestId:diagnostic.providerRequestId}:{}),...(diagnostic.errorClass?{errorClass:diagnostic.errorClass}:{}),...(diagnostic.errorCode?{errorCode:diagnostic.errorCode}:{}),...(diagnostic.httpStatus!==undefined?{httpStatus:diagnostic.httpStatus}:{}),...(diagnostic.retryAfter?{retryAfter:diagnostic.retryAfter}:{}),...(diagnostic.errorMessage?{errorMessage:diagnostic.errorMessage}:{})}}
function classify(error:unknown,afterResponse:boolean):{resultStatus:"PROVIDER_ERROR"|"SCHEMA_ERROR";schemaValid:boolean;providerRequestStarted:boolean;category:FinalSynthesisV2AttemptFailureCategory;reason?:FinalSynthesisVerifierV2Attempt["validationReason"];diagnostic?:SafeFailureDiagnostic}{if(error instanceof FinalSynthesisV2ProofValidationError)return{resultStatus:"SCHEMA_ERROR",schemaValid:true,providerRequestStarted:afterResponse,category:error.category,reason:error.reason};if(error instanceof z.ZodError)return{resultStatus:"SCHEMA_ERROR",schemaValid:false,providerRequestStarted:afterResponse,category:"STRUCTURED_OUTPUT_INVALID",diagnostic:safeDiagnostic(error)};if(error instanceof FinalSynthesisV2LocalRequestBuildError)return{resultStatus:"PROVIDER_ERROR",schemaValid:false,providerRequestStarted:false,category:"LOCAL_REQUEST_BUILD_ERROR",diagnostic:safeDiagnostic(error.original)};if(error instanceof FinalSynthesisV2ProviderInvocationError){const original=error.original;if(original instanceof Error&&original.message==="SCHEMA_INVALID")return{resultStatus:"SCHEMA_ERROR",schemaValid:false,providerRequestStarted:true,category:"STRUCTURED_OUTPUT_INVALID",diagnostic:safeDiagnostic(original)};if(original instanceof APIConnectionError)return{resultStatus:"PROVIDER_ERROR",schemaValid:false,providerRequestStarted:true,category:"NETWORK_OR_TRANSPORT_ERROR",diagnostic:safeDiagnostic(original)};if(original instanceof APIError)return{resultStatus:"PROVIDER_ERROR",schemaValid:false,providerRequestStarted:true,category:"PROVIDER_REQUEST_ERROR",diagnostic:safeDiagnostic(original)};return{resultStatus:"PROVIDER_ERROR",schemaValid:false,providerRequestStarted:true,category:"UNKNOWN_EXECUTION_ERROR",diagnostic:safeDiagnostic(original)}}return{resultStatus:"PROVIDER_ERROR",schemaValid:false,providerRequestStarted:afterResponse,category:"UNKNOWN_EXECUTION_ERROR",diagnostic:safeDiagnostic(error)}}
function safeDiagnostic(error:unknown):SafeFailureDiagnostic{if(!(error instanceof Error))return{};const api=error instanceof APIError?error:undefined;return{errorClass:safeScalar(error.constructor.name,80),...(api?.code?{errorCode:safeScalar(api.code,128)}:{}),...(typeof api?.status==="number"&&api.status>=100&&api.status<=599?{httpStatus:api.status}:{}),...(api?.requestID?{providerRequestId:safeScalar(api.requestID,200)}:{}),...(api?.headers?.get("retry-after")?{retryAfter:safeScalar(api.headers.get("retry-after")!,100)}:{}),...(error.message?{errorMessage:safeMessage(error.message)}:{})}}
function safeScalar(value:string,max:number){return Array.from(value,char=>{const code=char.charCodeAt(0);return code<32||code===127?" ":char}).join("").replace(/\s+/gu," ").trim().slice(0,max)}
function safeMessage(value:string){return safeScalar(value,2048).replace(/Bearer\s+\S+/giu,"Bearer [REDACTED]").replace(/\bsk-[A-Za-z0-9_-]+\b/gu,"[REDACTED]").replace(/OPENAI_API_KEY\s*[:=]\s*\S+/giu,"OPENAI_API_KEY=[REDACTED]").replace(/\b[A-Za-z0-9_-]{12,}\.[A-Za-z0-9_-]{12,}\.[A-Za-z0-9_-]{12,}\b/gu,"[REDACTED]").slice(0,512)}
