import OpenAI from "openai";
import { zodTextFormat } from "openai/helpers/zod";
import { z } from "zod";
import { FINAL_SYNTHESIS_V2_COMPONENT_MATCHES,FINAL_SYNTHESIS_V2_ENDORSEMENT_STATUSES,FINAL_SYNTHESIS_V2_REFERENCE_STATUSES,FinalSynthesisV2ExecutionError,FinalSynthesisV2ProofValidationError,validateFinalSynthesisV2ProofStructure,type FinalSynthesisVerifierV2Attempt,type FinalSynthesisVerifierV2Input,type FinalSynthesisVerifierV2Port,type UnvalidatedFinalSynthesisV2Proof } from "@/ports/final-synthesis-verifier-v2";
import { FINAL_SYNTHESIS_V2_PROMPT_VERSION,FINAL_SYNTHESIS_V2_SYSTEM_PROMPT } from "@/shared/final-synthesis-verifier-v2-prompt";

export interface FinalSynthesisV2ProofContract{readonly nodeId:string;readonly componentIds:readonly string[]}
export function buildFinalSynthesisV2ProviderSchema(contract:readonly FinalSynthesisV2ProofContract[],unitIds:readonly string[]){if(!contract.length||!unitIds.length)throw new Error("FINAL_SYNTHESIS_V2_PROVIDER_CONTRACT_EMPTY");const nodes=contract.map(({nodeId,componentIds})=>z.object({nodeId:z.literal(nodeId),components:z.array(z.object({componentId:z.enum(componentIds as [string,...string[]]),endorsementStatus:z.enum(FINAL_SYNTHESIS_V2_ENDORSEMENT_STATUSES),referenceStatus:z.enum(FINAL_SYNTHESIS_V2_REFERENCE_STATUSES),componentMatch:z.enum(FINAL_SYNTHESIS_V2_COMPONENT_MATCHES),evidenceUnitIds:z.array(z.enum(unitIds as [string,...string[]])).max(unitIds.length),antecedentEvidenceUnitIds:z.array(z.enum(unitIds as [string,...string[]])).max(unitIds.length)}).strict()).length(componentIds.length)}).strict());return z.object({nodes:z.tuple(nodes as [typeof nodes[number],...typeof nodes])}).strict()}
export interface OpenAIFinalSynthesisV2TransportRequest{readonly model:string;readonly promptVersion:typeof FINAL_SYNTHESIS_V2_PROMPT_VERSION;readonly systemPrompt:string;readonly input:string;readonly contract:readonly FinalSynthesisV2ProofContract[];readonly evidenceUnitIds:readonly string[]}
export interface OpenAIFinalSynthesisV2TransportResult{readonly output:unknown;readonly inputTokens?:number;readonly outputTokens?:number;readonly totalTokens?:number;readonly providerRequestId?:string}
export interface OpenAIFinalSynthesisV2Transport{extract(request:OpenAIFinalSynthesisV2TransportRequest):Promise<OpenAIFinalSynthesisV2TransportResult>}
export interface FinalSynthesisV2TransportExecutionObserver{recordTransportExecution():void}
export function buildOpenAIFinalSynthesisV2ClientOptions(apiKey:string):ConstructorParameters<typeof OpenAI>[0]{return{apiKey,maxRetries:0,logLevel:"off"}}
export function buildOpenAIFinalSynthesisV2ResponseRequest(request:OpenAIFinalSynthesisV2TransportRequest){return{model:request.model,instructions:request.systemPrompt,input:request.input,text:{format:zodTextFormat(buildFinalSynthesisV2ProviderSchema(request.contract,request.evidenceUnitIds),"g1_final_synthesis_v2")},store:false as const,tools:[],tool_choice:"none" as const}}
export function serializeFinalSynthesisV2SemanticInput(input:FinalSynthesisVerifierV2Input){return JSON.stringify({requiredNodes:input.requiredNodes,submission:input.submission,evidenceUnits:input.evidenceUnits})}
export class OpenAIResponsesFinalSynthesisV2Transport implements OpenAIFinalSynthesisV2Transport{private readonly client:OpenAI;constructor(apiKey:string){this.client=new OpenAI(buildOpenAIFinalSynthesisV2ClientOptions(apiKey))}async extract(request:OpenAIFinalSynthesisV2TransportRequest):Promise<OpenAIFinalSynthesisV2TransportResult>{const result=await this.client.responses.parse(buildOpenAIFinalSynthesisV2ResponseRequest(request)).withResponse();if(!result.data.output_parsed)throw new Error("SCHEMA_INVALID");const usage=result.data.usage;return{output:result.data.output_parsed,...(usage?{inputTokens:usage.input_tokens,outputTokens:usage.output_tokens,totalTokens:usage.total_tokens}:{}),...(result.request_id?{providerRequestId:result.request_id}:{})}}}
export class OpenAIFinalSynthesisVerifierV2Adapter implements FinalSynthesisVerifierV2Port{readonly promptVersion=FINAL_SYNTHESIS_V2_PROMPT_VERSION;constructor(private readonly transport:OpenAIFinalSynthesisV2Transport,private readonly model:string,private readonly executionObserver:FinalSynthesisV2TransportExecutionObserver,private readonly nowMs:()=>number=()=>performance.now()){}async extractProof(input:FinalSynthesisVerifierV2Input){const attempts:FinalSynthesisVerifierV2Attempt[]=[];const request:OpenAIFinalSynthesisV2TransportRequest={model:this.model,promptVersion:this.promptVersion,systemPrompt:FINAL_SYNTHESIS_V2_SYSTEM_PROMPT,input:serializeFinalSynthesisV2SemanticInput(input),contract:input.requiredNodes.map(node=>({nodeId:node.nodeId,componentIds:node.requiredComponents.map(component=>component.componentId)})),evidenceUnitIds:input.evidenceUnits.map(unit=>unit.unitId)};for(let attempt=1;attempt<=2;attempt++){const started=this.nowMs();let response:OpenAIFinalSynthesisV2TransportResult|undefined;try{this.executionObserver.recordTransportExecution();response=await this.transport.extract(request);const parsed=buildFinalSynthesisV2ProviderSchema(request.contract,request.evidenceUnitIds).parse(response.output) as UnvalidatedFinalSynthesisV2Proof;validateFinalSynthesisV2ProofStructure(parsed,input);attempts.push(meta(attempt,this.model,Math.max(0,Math.round(this.nowMs()-started)),"SUCCEEDED",true,response));return{proof:parsed,attempts}}catch(error){const failure=classify(error);attempts.push(meta(attempt,this.model,Math.max(0,Math.round(this.nowMs()-started)),failure.resultStatus,failure.schemaValid,response,failure.category,failure.reason))}}throw new FinalSynthesisV2ExecutionError(attempts)}}
function meta(attempt:number,model:string,latencyMs:number,resultStatus:FinalSynthesisVerifierV2Attempt["resultStatus"],schemaValid:boolean,response?:OpenAIFinalSynthesisV2TransportResult,failureCategory?:string,validationReason?:FinalSynthesisVerifierV2Attempt["validationReason"]):FinalSynthesisVerifierV2Attempt{return{attempt,provider:"openai",model,promptVersion:FINAL_SYNTHESIS_V2_PROMPT_VERSION,schemaValid,resultStatus,latencyMs,...(failureCategory?{failureCategory}:{}),...(validationReason?{validationReason}:{}),...(response?.inputTokens!==undefined?{inputTokens:response.inputTokens}:{}),...(response?.outputTokens!==undefined?{outputTokens:response.outputTokens}:{}),...(response?.totalTokens!==undefined?{totalTokens:response.totalTokens}:{}),...(response?.providerRequestId?{providerRequestId:response.providerRequestId}:{})}}
function classify(error:unknown):{resultStatus:"PROVIDER_ERROR"|"SCHEMA_ERROR";schemaValid:boolean;category:string;reason?:FinalSynthesisVerifierV2Attempt["validationReason"]}{if(error instanceof FinalSynthesisV2ProofValidationError)return{resultStatus:"SCHEMA_ERROR",schemaValid:true,category:error.category,reason:error.reason};if(error instanceof z.ZodError||(error instanceof Error&&error.message==="SCHEMA_INVALID"))return{resultStatus:"SCHEMA_ERROR",schemaValid:false,category:"STRUCTURED_OUTPUT_INVALID"};return{resultStatus:"PROVIDER_ERROR",schemaValid:false,category:"PROVIDER_UNAVAILABLE"}}
