import { describe,expect,it } from "vitest";
import { buildFinalSynthesisV2VerifierInput,deriveFinalSynthesisV2Verification,isFinalSynthesisV2Eligible } from "@/application/play/final-synthesis-proof-v2";
import { FINAL_SYNTHESIS_V2_COMPONENT_MATCHES,FINAL_SYNTHESIS_V2_ENDORSEMENT_STATUSES,FINAL_SYNTHESIS_V2_REFERENCE_STATUSES,validateFinalSynthesisV2ProofStructure } from "@/ports/final-synthesis-verifier-v2";
const nodes=[{nodeId:"NODE",requiredComponents:[{componentId:"COMP",description:"A complete component."}]}] as const;
const input=buildFinalSynthesisV2VerifierInput(nodes,"첫 구조가 있다. 그 구조가 결과 경계로 반복된다.");
const component=(overrides:Record<string,unknown>={})=>({componentId:"COMP",endorsementStatus:"ENDORSED",referenceStatus:"SELF_CONTAINED",componentMatch:"COMPLETE_COMPONENT_MATCH",evidenceUnitIds:["synthesis:u1"],antecedentEvidenceUnitIds:[],...overrides});
const proof=(value=component())=>({nodes:[{nodeId:"NODE",components:[value]}]});
describe("Final Synthesis proof v2",()=>{
 it("freezes the five-value orthogonal vocabularies",()=>{expect(FINAL_SYNTHESIS_V2_ENDORSEMENT_STATUSES).toContain("NOT_APPLICABLE");expect(FINAL_SYNTHESIS_V2_REFERENCE_STATUSES).toContain("NOT_APPLICABLE");expect(FINAL_SYNTHESIS_V2_COMPONENT_MATCHES).toHaveLength(5)});
 it("requires canonical empty evidence and not-applicable axes for no support",()=>{expect(()=>validateFinalSynthesisV2ProofStructure(proof(component({componentMatch:"NO_COMPONENT_SUPPORT",endorsementStatus:"NOT_APPLICABLE",referenceStatus:"NOT_APPLICABLE",evidenceUnitIds:[]})),input)).not.toThrow();expect(()=>validateFinalSynthesisV2ProofStructure(proof(component({componentMatch:"NO_COMPONENT_SUPPORT",evidenceUnitIds:[]})),input)).toThrow(/NO_SUPPORT_STATUS_INVALID/);expect(()=>validateFinalSynthesisV2ProofStructure(proof(component({componentMatch:"NO_COMPONENT_SUPPORT",endorsementStatus:"NOT_APPLICABLE",referenceStatus:"NOT_APPLICABLE"})),input)).toThrow(/NO_SUPPORT_EVIDENCE_FORBIDDEN/)});
 it("rejects not-applicable axes on every supported match",()=>{for(const match of ["COMPLETE_COMPONENT_MATCH","WEAKER_THAN_COMPONENT_REQUIREMENT","PARTIAL_COMPONENT_MATCH","CONTRADICTS_COMPONENT"])expect(()=>validateFinalSynthesisV2ProofStructure(proof(component({componentMatch:match,endorsementStatus:"NOT_APPLICABLE"})),input)).toThrow(/NON_NO_SUPPORT_STATUS_REQUIRED/)});
 it.each(["COMPLETE_COMPONENT_MATCH","WEAKER_THAN_COMPONENT_REQUIREMENT","PARTIAL_COMPONENT_MATCH","CONTRADICTS_COMPONENT"])("requires evidence for %s",match=>expect(()=>validateFinalSynthesisV2ProofStructure(proof(component({componentMatch:match,evidenceUnitIds:[]})),input)).toThrow(/NON_NO_SUPPORT_EVIDENCE_REQUIRED/));
 it("keeps endorsement and reference independent from local match",()=>{expect(()=>validateFinalSynthesisV2ProofStructure(proof(component({endorsementStatus:"REJECTED_OR_QUOTED"})),input)).not.toThrow();expect(()=>validateFinalSynthesisV2ProofStructure(proof(component({referenceStatus:"AMBIGUOUS"})),input)).not.toThrow();expect(()=>validateFinalSynthesisV2ProofStructure(proof(component({referenceStatus:"UNRESOLVED"})),input)).not.toThrow()});
 it("requires unique earlier synthesis antecedents only for resolved references",()=>{expect(()=>validateFinalSynthesisV2ProofStructure(proof(component({referenceStatus:"RESOLVED_WITHIN_SYNTHESIS",evidenceUnitIds:["synthesis:u2"],antecedentEvidenceUnitIds:["synthesis:u1"]})),input)).not.toThrow();expect(()=>validateFinalSynthesisV2ProofStructure(proof(component({referenceStatus:"RESOLVED_WITHIN_SYNTHESIS",evidenceUnitIds:["synthesis:u1"],antecedentEvidenceUnitIds:["synthesis:u2"]})),input)).toThrow(/ANTECEDENT_NOT_EARLIER/)});
 it("derives satisfaction only from the unchanged three-way conjunction",()=>{const verified=deriveFinalSynthesisV2Verification(proof(),input);expect(isFinalSynthesisV2Eligible(verified)).toBe(true);for(const value of [component({endorsementStatus:"REJECTED_OR_QUOTED"}),component({referenceStatus:"AMBIGUOUS"}),component({componentMatch:"WEAKER_THAN_COMPONENT_REQUIREMENT"}),component({componentMatch:"NO_COMPONENT_SUPPORT",endorsementStatus:"NOT_APPLICABLE",referenceStatus:"NOT_APPLICABLE",evidenceUnitIds:[]})])expect(isFinalSynthesisV2Eligible(deriveFinalSynthesisV2Verification(proof(value),input))).toBe(false)});
 it("does not derive a missing constituent from a complete relation component",()=>{const two=buildFinalSynthesisV2VerifierInput([{nodeId:"NODE",requiredComponents:[{componentId:"CONSTITUENT",description:"explicit constituent"},{componentId:"RELATION",description:"complete relation"}]}],"두 구조가 대응한다");const candidate={nodes:[{nodeId:"NODE",components:[{componentId:"CONSTITUENT",endorsementStatus:"NOT_APPLICABLE",referenceStatus:"NOT_APPLICABLE",componentMatch:"NO_COMPONENT_SUPPORT",evidenceUnitIds:[],antecedentEvidenceUnitIds:[]},{componentId:"RELATION",endorsementStatus:"ENDORSED",referenceStatus:"SELF_CONTAINED",componentMatch:"COMPLETE_COMPONENT_MATCH",evidenceUnitIds:["synthesis:u1"],antecedentEvidenceUnitIds:[]}]}]};const result=deriveFinalSynthesisV2Verification(candidate,two);expect(result.nodes[0]?.components).toEqual([{componentId:"CONSTITUENT",satisfied:false},{componentId:"RELATION",satisfied:true}]);expect(isFinalSynthesisV2Eligible(result)).toBe(false)});
});
