import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { describe,expect,it,vi } from "vitest";
import { buildFinalSynthesisV2VerifierInput,deriveFinalSynthesisV2Verification } from "@/application/play/final-synthesis-proof-v2";
import { FinalSynthesisV2ExecutionError,type FinalSynthesisVerifierV2Attempt } from "@/ports/final-synthesis-verifier-v2";
import { OpenAIFinalSynthesisVerifierV2Adapter,type OpenAIFinalSynthesisV2Transport } from "@/adapters/openai-final-synthesis-verifier-v2/openai-final-synthesis-verifier-v2";
import { FINAL_SYNTHESIS_V2_SYSTEM_PROMPT } from "@/shared/final-synthesis-verifier-v2-prompt";
import { FINAL_SYNTHESIS_SYSTEM_PROMPT } from "@/shared/final-synthesis-verifier-prompt";
import { buildFinalSynthesisV2EvaluationReport,loadFinalSynthesisV2DevelopmentSuite,preflightFinalSynthesisV2DevelopmentSuite,scanFinalSynthesisV2ReportLeakage,toEvaluatedV2,type EvaluatedV2Case,type FinalSynthesisV2ProviderExecutionSnapshot } from "../../tooling/final-synthesis-v2-eval.mts";

const nodes=[{nodeId:"NODE",requiredComponents:[{componentId:"COMP",description:"complete"}]}] as const;
const input=buildFinalSynthesisV2VerifierInput(nodes,"명시된 완전한 결론이다");
const complete={nodes:[{nodeId:"NODE",components:[{componentId:"COMP",endorsementStatus:"ENDORSED" as const,referenceStatus:"SELF_CONTAINED" as const,componentMatch:"COMPLETE_COMPONENT_MATCH" as const,evidenceUnitIds:["synthesis:u1"],antecedentEvidenceUnitIds:[]}]}]};
const observer=()=>({recordTransportExecution:vi.fn()});

async function validFixture(){
  const suite=await loadFinalSynthesisV2DevelopmentSuite();
  const attempt:FinalSynthesisVerifierV2Attempt={attempt:1,provider:"fake",model:"unselected-test",promptVersion:"final-synthesis-verify-v2",schemaValid:true,resultStatus:"SUCCEEDED",latencyMs:1};
  const rows=suite.cases.map(item=>{
    const localInput=buildFinalSynthesisV2VerifierInput(suite.requiredNodes,item.synthesis);
    const proof={nodes:suite.requiredNodes.map(node=>({nodeId:node.nodeId,components:node.requiredComponents.map(component=>{
      const fact=item.gold_proof_facts.find(value=>value.component_id===component.componentId)!;
      return{componentId:component.componentId,endorsementStatus:fact.endorsement_status,referenceStatus:fact.reference_status,componentMatch:fact.component_match,evidenceUnitIds:fact.evidence_unit_ids,antecedentEvidenceUnitIds:fact.antecedent_evidence_unit_ids};
    })}))};
    return toEvaluatedV2(item,deriveFinalSynthesisV2Verification(proof,localInput),proof,[attempt]);
  });
  const byCase=Object.fromEntries(rows.map(row=>[row.caseId,1]));
  return{suite,rows,execution:{total:rows.length,byCase} satisfies FinalSynthesisV2ProviderExecutionSnapshot};
}

function reportOf(fixture:Awaited<ReturnType<typeof validFixture>>,rows=fixture.rows,execution=fixture.execution){
  return buildFinalSynthesisV2EvaluationReport(fixture.suite.cases,rows,fixture.suite.manifest.required_regression_case_ids,fixture.suite.requiredNodes,execution);
}

describe("Final Synthesis evaluator v2",()=>{
  it("loads 96 cases, validates 480 component gold facts, and keeps the candidate unselected",async()=>{const suite=await loadFinalSynthesisV2DevelopmentSuite(),p=await preflightFinalSynthesisV2DevelopmentSuite();expect(p).toMatchObject({datasetVersion:"final-synthesis-dev-v2",proofVersion:"final-synthesis-proof-v2",evaluatorVersion:"final-synthesis-eval-v2",caseCount:96,positiveCount:32,negativeCount:64,singleUnitCount:48,multiUnitCount:48,criticalCount:24,candidateModel:"UNSELECTED",goldConsistency:{expected:480,valid:480}});expect(suite.ledger.entries).toHaveLength(96);expect(new Set(suite.ledger.entries.map(x=>x.v2_case_id)).size).toBe(96);expect(p.axis).toMatchObject({quotedComplete:4,ambiguousComplete:4,unresolvedComplete:4,correctionCurrent:4,abandoned:4});expect(p.axis.relationNoConstituents).toBeGreaterThanOrEqual(6);expect(p.axis.noSupport).toBeGreaterThanOrEqual(8)});
  it("retains recovered failure reason and response telemetry",async()=>{let n=0;const transport={extract:vi.fn(async()=>{n++;return{output:n===1?{nodes:[{nodeId:"NODE",components:[{...complete.nodes[0]!.components[0]!,evidenceUnitIds:[]}]}]}:complete,inputTokens:10,outputTokens:2,totalTokens:12,providerRequestId:`r${n}`}})} satisfies OpenAIFinalSynthesisV2Transport;const executionObserver=observer();const result=await new OpenAIFinalSynthesisVerifierV2Adapter(transport,"model",executionObserver,()=>1).extractProof(input);expect(executionObserver.recordTransportExecution).toHaveBeenCalledTimes(2);expect(result.attempts).toHaveLength(2);expect(result.attempts[0]).toMatchObject({resultStatus:"SCHEMA_ERROR",failureCategory:"PROOF_RECORD_INVALID",validationReason:"NON_NO_SUPPORT_EVIDENCE_REQUIRED",inputTokens:10,outputTokens:2,totalTokens:12,providerRequestId:"r1"});expect(result.attempts[1]).toMatchObject({resultStatus:"SUCCEEDED",providerRequestId:"r2"})});
  it("retains terminal diagnostics after both failures",async()=>{const invalid={nodes:[{nodeId:"NODE",components:[{...complete.nodes[0]!.components[0]!,evidenceUnitIds:[]}]}]};const transport={extract:vi.fn(async()=>({output:invalid}))} satisfies OpenAIFinalSynthesisV2Transport;try{await new OpenAIFinalSynthesisVerifierV2Adapter(transport,"model",observer(),()=>1).extractProof(input);throw new Error("expected failure")}catch(error){expect(error).toBeInstanceOf(FinalSynthesisV2ExecutionError);expect((error as FinalSynthesisV2ExecutionError).attempts).toHaveLength(2);expect((error as FinalSynthesisV2ExecutionError).attempts.every(x=>x.failureCategory&&x.validationReason)).toBe(true)}});
  it("fails independent total accounting when one of two transported attempts is omitted from the artifact",async()=>{const f=await validFixture(),rows=[...f.rows],id=rows[0]!.caseId;const recovered:FinalSynthesisVerifierV2Attempt={...rows[0]!.attempts[0]!,attempt:1,resultStatus:"SCHEMA_ERROR",schemaValid:false,failureCategory:"PROOF_RECORD_INVALID",validationReason:"NON_NO_SUPPORT_EVIDENCE_REQUIRED"};rows[0]={...rows[0]!,attempts:[recovered,{...rows[0]!.attempts[0]!,attempt:2}]};const execution={total:f.execution.total+1,byCase:{...f.execution.byCase,[id]:2}};const completeReport=reportOf(f,rows,execution);expect(completeReport.hardGates.attemptAccounting).toBe(true);expect(completeReport.hardGates.perCaseAttemptAccounting).toBe(true);rows[0]={...rows[0]!,attempts:rows[0]!.attempts.slice(1)};expect(reportOf(f,rows,execution).hardGates.attemptAccounting).toBe(false)});
  it("fails per-case accounting when a recovered first attempt is omitted",async()=>{const f=await validFixture(),rows=[...f.rows],id=rows[0]!.caseId;const execution={total:f.execution.total+1,byCase:{...f.execution.byCase,[id]:2}};rows[0]={...rows[0]!,attempts:[{...rows[0]!.attempts[0]!,attempt:2}]};expect(reportOf(f,rows,execution).hardGates.perCaseAttemptAccounting).toBe(false)});
  it("fails malformed attempt sequences",async()=>{const f=await validFixture(),rows=[...f.rows];rows[0]={...rows[0]!,attempts:[{...rows[0]!.attempts[0]!,attempt:2}]};expect(reportOf(f,rows).hardGates.attemptSequence).toBe(false)});
  it("fails unavailable terminal records without a failure category",async()=>{const f=await validFixture(),rows=[...f.rows];rows[0]={...rows[0]!,unavailable:true,schemaApplicationValid:false,predictedEligible:false,predictedNodes:{},predictedComponents:{},proofFacts:[],attempts:[{...rows[0]!.attempts[0]!,resultStatus:"SCHEMA_ERROR",schemaValid:false}]};expect(reportOf(f,rows).hardGates.terminalDiagnostics).toBe(false)});
  it("fails application validation attempts without the exact reason",async()=>{const f=await validFixture(),rows=[...f.rows];rows[0]={...rows[0]!,attempts:[{...rows[0]!.attempts[0]!,resultStatus:"SCHEMA_ERROR",failureCategory:"PROOF_RECORD_INVALID"}]};expect(reportOf(f,rows).hardGates.validationReasonsComplete).toBe(false)});
  it("fails missing, duplicate, and unknown component proof facts",async()=>{const f=await validFixture();for(const mutate of [(x:EvaluatedV2Case)=>({...x,proofFacts:x.proofFacts.slice(1)}),(x:EvaluatedV2Case)=>({...x,proofFacts:[...x.proofFacts,x.proofFacts[0]!]}),(x:EvaluatedV2Case)=>({...x,proofFacts:[...x.proofFacts.slice(0,-1),{...x.proofFacts.at(-1)!,componentId:"UNKNOWN"}]})]){const rows=[...f.rows];rows[0]=mutate(rows[0]!) as EvaluatedV2Case;expect(reportOf(f,rows).hardGates.proofCompleteness).toBe(false)}});
  it("fails corrupted component satisfaction and node support",async()=>{const f=await validFixture();const rows1=[...f.rows];rows1[0]={...rows1[0]!,proofFacts:rows1[0]!.proofFacts.map((x,i)=>i?x:{...x,satisfied:!x.satisfied})};expect(reportOf(f,rows1).hardGates.derivedConsistency).toBe(false);const rows2=[...f.rows],nodeId=Object.keys(rows2[0]!.predictedNodes)[0]!;rows2[0]={...rows2[0]!,predictedNodes:{...rows2[0]!.predictedNodes,[nodeId]:!rows2[0]!.predictedNodes[nodeId]}};expect(reportOf(f,rows2).hardGates.derivedConsistency).toBe(false)});
  it("retains complete redacted proof facts without raw text",async()=>{const f=await validFixture(),report=reportOf(f);expect(report.operational.independentActualProviderExecutions).toBe(report.operational.attemptRecordCount);expect(report.cases.every(x=>x.proofFacts.length===5)).toBe(true);expect(JSON.stringify(report)).not.toContain(f.suite.cases[0]!.synthesis);expect(scanFinalSynthesisV2ReportLeakage(report,f.suite.cases)).toBe(0)});
  it("keeps prompt examples abstract and freezes canonical proposition precedence",()=>{expect(FINAL_SYNTHESIS_V2_SYSTEM_PROMPT).toMatch(/orthogonal/);expect(FINAL_SYNTHESIS_V2_SYSTEM_PROMPT).toMatch(/Select exactly one canonical component proposition/);expect(FINAL_SYNTHESIS_V2_SYSTEM_PROMPT).toMatch(/current replacement: ENDORSED with CONTRADICTS_COMPONENT/);expect(FINAL_SYNTHESIS_V2_SYSTEM_PROMPT).toMatch(/cannot by itself establish/)});
  it("keeps live-consumed v1 prompt, corpus, and manifest identities immutable",async()=>{const hash=(value:string|Buffer)=>createHash("sha256").update(value).digest("hex");expect(hash(FINAL_SYNTHESIS_SYSTEM_PROMPT)).toBe("006a068831f4a18bb62301eb4e0067b9cdce9c6bf40afb720e76c4d07f88e502");expect(hash(await readFile("eval/final-synthesis/v1/cases.jsonl"))).toBe("e3328704afdb2f6234363935b61e368f6dfa9bae828d70423fb986bfd0ed9cd1");const manifest=JSON.parse(await readFile("eval/final-synthesis/v1/manifest.json","utf8"));expect(manifest).toMatchObject({dataset_version:"final-synthesis-dev-v1",prompt_version:"final-synthesis-verify-v1",proof_contract_version:"final-synthesis-proof-v1",evaluator_version:"final-synthesis-eval-v1"})});
});
