import { describe,expect,it,vi } from "vitest";
import { buildFinalSynthesisVerifierInput,deriveFinalSynthesisVerification,isFinalSynthesisEligible } from "@/application/play/final-synthesis-proof";
import { FinalSynthesisExecutionError } from "@/ports/final-synthesis-verifier";
import { FINAL_SYNTHESIS_PROMPT_VERSION,FINAL_SYNTHESIS_SYSTEM_PROMPT } from "@/shared/final-synthesis-verifier-prompt";
import { OpenAIFinalSynthesisVerifierAdapter,buildFinalSynthesisProviderSchema,buildOpenAIFinalSynthesisClientOptions,buildOpenAIFinalSynthesisResponseRequest,serializeFinalSynthesisSemanticInput,type OpenAIFinalSynthesisTransport } from "@/adapters/openai-final-synthesis-verifier/openai-final-synthesis-verifier";

const requiredNodes=[{nodeId:"NODE",requiredComponents:[{componentId:"COMPONENT",description:"An explicit complete relation."}]}] as const;
const input=buildFinalSynthesisVerifierInput(requiredNodes,"A complete relation is explicit.");
const complete={nodes:[{nodeId:"NODE",components:[{componentId:"COMPONENT",endorsementStatus:"ENDORSED",referenceStatus:"SELF_CONTAINED",componentMatch:"COMPLETE_COMPONENT_MATCH",evidenceUnitIds:["synthesis:u1"],antecedentEvidenceUnitIds:[]}]}]};
const insufficient={nodes:[{nodeId:"NODE",components:[{componentId:"COMPONENT",endorsementStatus:"ENDORSED",referenceStatus:"SELF_CONTAINED",componentMatch:"NO_COMPONENT_SUPPORT",evidenceUnitIds:[],antecedentEvidenceUnitIds:[]}]}]};
function transport(outputs:readonly (unknown|Error)[]){let index=0;return{extract:vi.fn(async()=>{const value=outputs[index++];if(value instanceof Error)throw value;return{output:value}})} satisfies OpenAIFinalSynthesisTransport}

describe("OpenAI Final Synthesis verifier adapter",()=>{
  it("pins SDK privacy and retry options and the immutable prompt",()=>{expect(buildOpenAIFinalSynthesisClientOptions("secret")).toEqual({apiKey:"secret",maxRetries:0,logLevel:"off"});const request=buildOpenAIFinalSynthesisResponseRequest({model:"explicit-model",promptVersion:FINAL_SYNTHESIS_PROMPT_VERSION,systemPrompt:FINAL_SYNTHESIS_SYSTEM_PROMPT,input:"{}",contract:[{nodeId:"NODE",componentIds:["COMPONENT"]}],evidenceUnitIds:["synthesis:u1"]});expect(request).toMatchObject({model:"explicit-model",instructions:FINAL_SYNTHESIS_SYSTEM_PROMPT,store:false,tools:[],tool_choice:"none"})});
  it("explicitly excludes Judge state and common-sense gap filling",()=>{expect(FINAL_SYNTHESIS_SYSTEM_PROMPT).toMatch(/Judge state or verdicts/);expect(FINAL_SYNTHESIS_SYSTEM_PROMPT).toMatch(/common sense/)});
  it("serializes only the approved semantic authority",()=>{const parsed=JSON.parse(serializeFinalSynthesisSemanticInput(input));expect(Object.keys(parsed)).toEqual(["requiredNodes","submission","evidenceUnits"]);expect(JSON.stringify(parsed)).not.toMatch(/expected|rationale|previous|judge|guidance|reveal|priorConfirmedState/i)});
  it("uses a strict dynamic contract without a binary verdict escape hatch",()=>{const schema=buildFinalSynthesisProviderSchema([{nodeId:"NODE",componentIds:["COMPONENT"]}],["synthesis:u1"]);expect(()=>schema.parse({...complete,eligible:true})).toThrow();expect(()=>schema.parse({nodes:[{...complete.nodes[0]!,nodeId:"OTHER"}]})).toThrow();expect(()=>schema.parse({nodes:[{nodeId:"NODE",components:[{...complete.nodes[0]!.components[0]!,evidenceUnitIds:["synthesis:u2"]}]}]})).toThrow()});
  it("accepts a valid proof and leaves eligibility to deterministic derivation",async()=>{const fake=transport([complete]);const result=await new OpenAIFinalSynthesisVerifierAdapter(fake,"explicit-model",()=>1).extractProof(input);expect(fake.extract).toHaveBeenCalledTimes(1);expect(isFinalSynthesisEligible(deriveFinalSynthesisVerification(result.proof,input))).toBe(true)});
  it.each([["malformed",{}],["invalid proof",{nodes:[{...complete.nodes[0]!,components:[{...complete.nodes[0]!.components[0]!,evidenceUnitIds:[]}]}]}],["provider failure",new Error("offline")]])("retries %s exactly once",async(_name,first)=>{const fake=transport([first,complete]);const result=await new OpenAIFinalSynthesisVerifierAdapter(fake,"model",()=>1).extractProof(input);expect(fake.extract).toHaveBeenCalledTimes(2);expect(result.attempts).toHaveLength(2)});
  it("throws a typed execution error after the second failure",async()=>{const fake=transport([new Error("offline"),new Error("offline")]);await expect(new OpenAIFinalSynthesisVerifierAdapter(fake,"model",()=>1).extractProof(input)).rejects.toBeInstanceOf(FinalSynthesisExecutionError);expect(fake.extract).toHaveBeenCalledTimes(2)});
  it("does not retry a structurally valid semantic insufficiency",async()=>{const fake=transport([insufficient]);const result=await new OpenAIFinalSynthesisVerifierAdapter(fake,"model",()=>1).extractProof(input);expect(fake.extract).toHaveBeenCalledTimes(1);expect(isFinalSynthesisEligible(deriveFinalSynthesisVerification(result.proof,input))).toBe(false)});
  it("keeps attempt metadata free of raw submission, prompt, and provider body",async()=>{const result=await new OpenAIFinalSynthesisVerifierAdapter(transport([complete]),"model",()=>1).extractProof(input);const serialized=JSON.stringify(result.attempts);expect(serialized).not.toContain(input.submission.text);expect(serialized).not.toContain(FINAL_SYNTHESIS_SYSTEM_PROMPT);expect(serialized).not.toContain("A complete relation")});
});
