import { mkdir,writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { tmpdir } from "node:os";
import path from "node:path";
import { describe,expect,it,vi } from "vitest";
import { FINAL_SYNTHESIS_PROMPT_VERSION } from "@/shared/final-synthesis-verifier-prompt";
import { FINAL_SYNTHESIS_PROOF_CONTRACT_VERSION } from "@/ports/final-synthesis-verifier";
import { assertFinalSynthesisCaseIdentity,auditFinalSynthesisCorpus,buildFinalSynthesisEvaluationReport,loadFinalSynthesisDevelopmentSuite,parseFinalSynthesisManifest,preflightFinalSynthesisDevelopmentSuite,runFinalSynthesisLiveEvaluation,scanFinalSynthesisReportLeakage,validateFinalSynthesisIdentityHashes,validateFinalSynthesisRunContract,type EvaluatedCase,type FinalSynthesisRunSealDependencies } from "../../tooling/final-synthesis-eval.mts";

describe("Final Synthesis development corpus and evaluator",()=>{
  it("validates exact identities, composition, fresh component contract, and no selected model",async()=>{const suite=await loadFinalSynthesisDevelopmentSuite();const preflight=await preflightFinalSynthesisDevelopmentSuite();expect(preflight).toMatchObject({caseCount:96,positiveCount:32,negativeCount:64,singleUnitCount:48,multiUnitCount:48,criticalRegressionCount:24,candidateModel:"UNSELECTED"});expect(Object.keys(suite.manifest)).not.toContain("candidate_model");expect(suite.componentIds).toHaveLength(5);expect(new Set(suite.cases.map(x=>x.id)).size).toBe(96);expect(new Set(suite.cases.map(x=>x.synthesis.trim().replace(/\s+/gu," "))).size).toBe(96);expect(Math.max(...suite.cases.map(x=>x.synthesis.length))).toBeLessThanOrEqual(500);expect(Object.values(preflight.componentChallengeCounts).every(count=>count>=8)).toBe(true)});
  it("enforces long-input, long-reference, and failure-signature corpus validity",async()=>{const preflight=await preflightFinalSynthesisDevelopmentSuite();expect(preflight.length.bands.from100To199).toBeGreaterThanOrEqual(10);expect(preflight.length.bands.from200To299).toBeGreaterThanOrEqual(6);expect(preflight.length.bands.from300To399).toBeGreaterThanOrEqual(4);expect(preflight.length.bands.from400To500).toBeGreaterThanOrEqual(4);expect(preflight.length.bands.nearLimit).toBeGreaterThanOrEqual(2);expect(preflight.length.bands.positiveLong).toBeGreaterThanOrEqual(8);expect(preflight.length.bands.negativeLong).toBeGreaterThanOrEqual(16);expect(preflight.length.max).toBeLessThanOrEqual(500);expect(preflight.referenceLength).toMatchObject({ambiguous100:2,ambiguous200:1,unresolved100:2,unresolved200:1});expect(preflight.negative.structuralCorrespondenceTrue).toBeGreaterThanOrEqual(12);expect(preflight.negative.uniqueFailureSignatures).toBeGreaterThanOrEqual(8);expect(preflight.negative.largestSignatureRatio).toBeLessThanOrEqual(.5)});
  it("enforces newline, noisy text, long references, unicode, and truthful primary categories",async()=>{const preflight=await preflightFinalSynthesisDevelopmentSuite();expect(preflight.format.newline).toBeGreaterThanOrEqual(4);expect(preflight.format.spellingSpacing).toBeGreaterThanOrEqual(6);expect(preflight.format.longDistanceReference).toBeGreaterThanOrEqual(4);expect(preflight.format.emojiUnicodeMulti).toBeGreaterThanOrEqual(2);expect(preflight.format.promptInjection).toBeGreaterThan(0);expect(preflight.format.longPromptInjection).toBeGreaterThan(0);const suite=await loadFinalSynthesisDevelopmentSuite();for(const item of suite.cases){expect(item.tags[0]).toBe(item.expected_eligible?"positive":"negative");expect(item.tags[1]).toBe(item.unit_shape)}for(const id of ["fs-negative-single-14","fs-negative-multi-11","fs-negative-multi-12","fs-negative-multi-13","fs-negative-multi-18","fs-negative-multi-19"]){expect(suite.cases.find(item=>item.id===id)?.primary_category).toMatch(/quotation-rejection|correction|contradiction|prompt-injection/)} });
  it("rejects a spacing-noise tag when its reviewed raw surface is removed",async()=>{const suite=await loadFinalSynthesisDevelopmentSuite();const cases=suite.cases.map(item=>item.id==="fs-negative-single-24"?{...item,synthesis:"사람들이 한 팀이고 대화를 한다"}:item);expect(()=>auditFinalSynthesisCorpus(cases,suite.componentIds,suite.manifest.required_regression_case_ids)).toThrow(/SPACING_NOISE_SURFACE/)});
  it("keeps critical reference and match axes independent",async()=>{const suite=await loadFinalSynthesisDevelopmentSuite();for(const [id,reference] of [["fs-negative-multi-15","AMBIGUOUS"],["fs-negative-multi-32","UNRESOLVED"]] as const){const item=suite.cases.find(value=>value.id===id)!;expect(item.expected_proof_facts).toEqual([expect.objectContaining({reference_status:reference,component_match:"COMPLETE_COMPONENT_MATCH",antecedent_evidence_unit_ids:[]})])}});
  it("pins corrected critical evidence to the actual structural proposition units",async()=>{const suite=await loadFinalSynthesisDevelopmentSuite();for(const [id,evidence] of [["fs-positive-multi-01","synthesis:u3"],["fs-positive-multi-03","synthesis:u3"],["fs-positive-multi-04","synthesis:u4"]] as const){expect(suite.cases.find(item=>item.id===id)?.expected_proof_facts?.[0]?.evidence_unit_ids).toEqual([evidence])}expect(suite.manifest.required_regression_case_ids).not.toContain("fs-negative-single-15");expect(suite.manifest.required_regression_case_ids).toContain("fs-negative-single-09")});
  it("contains injection, unresolved, ambiguous, quote, correction, and structural-boundary cases",async()=>{const texts=(await loadFinalSynthesisDevelopmentSuite()).cases.map(x=>`${x.tags.join(" ")} ${x.synthesis}`).join("\n");expect(texts).toMatch(/지시|JSON|system/);expect(texts).toMatch(/아까|그것/);expect(texts).toMatch(/후보/);expect(texts).toMatch(/인용|버렸다/);expect(texts).toMatch(/다시 정리|잘못/);expect(texts).toMatch(/영향|대응|반영/)});
  it("rejects normalized duplicate text, non-exact critical count, and manifest identity/model drift",async()=>{expect(()=>assertFinalSynthesisCaseIdentity([{id:"a",synthesis:"같은  문장"},{id:"b",synthesis:" 같은 문장 "}])).toThrow(/NORMALIZED_DUPLICATE/);const suite=await loadFinalSynthesisDevelopmentSuite();expect(()=>parseFinalSynthesisManifest({...suite.manifest,required_regression_case_ids:[...suite.manifest.required_regression_case_ids,"extra"]})).toThrow();expect(()=>parseFinalSynthesisManifest({...suite.manifest,evaluator_version:"other"})).toThrow();expect(()=>parseFinalSynthesisManifest({...suite.manifest,candidate_model:"model"})).toThrow()});
  it("rejects corpus, prompt, and content hash drift before evaluation",async()=>{const suite=await loadFinalSynthesisDevelopmentSuite();const corpus=Buffer.from("frozen corpus");const corpusHash=createHash("sha256").update(corpus).digest("hex");expect(()=>validateFinalSynthesisIdentityHashes({...suite.manifest,corpus_sha256:"0".repeat(64)},corpus,"prompt",suite.contentHash)).toThrow(/CORPUS/);expect(()=>validateFinalSynthesisIdentityHashes({...suite.manifest,corpus_sha256:corpusHash},corpus,"drift",suite.contentHash)).toThrow(/PROMPT/);expect(()=>validateFinalSynthesisIdentityHashes({...suite.manifest,corpus_sha256:corpusHash,prompt_sha256:createHash("sha256").update("prompt").digest("hex")},corpus,"prompt","f".repeat(64))).toThrow(/CONTENT/)});
  it("makes a single false approval non-compensable",async()=>{const suite=await loadFinalSynthesisDevelopmentSuite();const rows=perfectRows(suite.cases,suite.requiredNodes);const firstNegative=rows.findIndex(x=>!x.expectedEligible);rows[firstNegative]={...rows[firstNegative]!,predictedEligible:true};const report=buildFinalSynthesisEvaluationReport(suite.cases,rows,suite.manifest.required_regression_case_ids);expect(report.approval.fp).toBe(1);expect(report.hardGates.falseApprovals).toBe(false);expect(report.accepted).toBe(false)});
  it("enforces recall and retry integer boundaries",async()=>{const suite=await loadFinalSynthesisDevelopmentSuite();const rows=perfectRows(suite.cases,suite.requiredNodes);for(const row of rows.filter(x=>x.expectedEligible).slice(0,5)){const index=rows.indexOf(row);rows[index]={...row,predictedEligible:false}}for(const row of rows.slice(0,4)){const index=rows.indexOf(row);rows[index]={...rows[index]!,retried:true}}let report=buildFinalSynthesisEvaluationReport(suite.cases,rows,suite.manifest.required_regression_case_ids);expect(report.approval.tp).toBe(27);expect(report.hardGates.approvalRecall).toBe(false);expect(report.hardGates.retryRate).toBe(true);rows[4]={...rows[4]!,retried:true};report=buildFinalSynthesisEvaluationReport(suite.cases,rows,suite.manifest.required_regression_case_ids);expect(report.hardGates.retryRate).toBe(false)});
  it("redacts report data and detects synthesis leakage",async()=>{const suite=await loadFinalSynthesisDevelopmentSuite();const report=buildFinalSynthesisEvaluationReport(suite.cases,perfectRows(suite.cases,suite.requiredNodes),suite.manifest.required_regression_case_ids);expect(scanFinalSynthesisReportLeakage(report,suite.cases)).toBe(0);expect(scanFinalSynthesisReportLeakage({raw:suite.cases[0]!.synthesis},suite.cases)).toBe(1);expect(JSON.stringify(report)).not.toContain(suite.cases[0]!.synthesis)});
  it("fails before provider construction when opt-in or frozen run contract is absent",async()=>{const makeVerifier=vi.fn();await expect(runFinalSynthesisLiveEvaluation({env:{},makeVerifier})).rejects.toThrow(/LIVE_OPT_IN/);expect(makeVerifier).not.toHaveBeenCalled()});
  it("rejects wrong git and model contracts before provider construction",async()=>{const fixture=await sealedFixture();const makeVerifier=vi.fn();await expect(runFinalSynthesisLiveEvaluation({env:fixture.env,sealDependencies:fixture.deps,makeVerifier})).rejects.toThrow(/git_sha/);expect(makeVerifier).not.toHaveBeenCalled();fixture.contract.git_sha=fixture.head;await writeFile(fixture.file,JSON.stringify(fixture.contract));await expect(runFinalSynthesisLiveEvaluation({env:{...fixture.env,FINAL_SYNTHESIS_MODEL:"wrong-model"},sealDependencies:fixture.deps,makeVerifier})).rejects.toThrow(/candidate_model/);expect(makeVerifier).not.toHaveBeenCalled()});
  it("rejects a dirty worktree before provider construction",async()=>{const fixture=await sealedFixture();fixture.contract.git_sha=fixture.head;await writeFile(fixture.file,JSON.stringify(fixture.contract));const makeVerifier=vi.fn();const deps={...fixture.deps,runGit:gitFake(fixture.head,{dirty:true})};await expect(runFinalSynthesisLiveEvaluation({env:fixture.env,sealDependencies:deps,makeVerifier})).rejects.toThrow(/WORKTREE_NOT_CLEAN/);expect(makeVerifier).not.toHaveBeenCalled()});
  it("rejects arbitrary, outside-root, traversal, tracked, and non-ignored contract paths before provider construction",async()=>{const fixture=await sealedFixture();fixture.contract.git_sha=fixture.head;await writeFile(fixture.file,JSON.stringify(fixture.contract));const makeVerifier=vi.fn();for(const candidate of [path.join(fixture.repo,"contract.json"),path.join(fixture.repo,"..","outside-contract.json"),path.join(fixture.root,"..","escape.json")]){await writeFile(candidate,JSON.stringify(fixture.contract));await expect(runFinalSynthesisLiveEvaluation({env:{...fixture.env,FINAL_SYNTHESIS_RUN_CONTRACT:candidate},sealDependencies:fixture.deps,makeVerifier})).rejects.toThrow(/PATH_INVALID/)}await expect(runFinalSynthesisLiveEvaluation({env:fixture.env,sealDependencies:{...fixture.deps,runGit:gitFake(fixture.head,{tracked:true})},makeVerifier})).rejects.toThrow(/TRACKED/);await expect(runFinalSynthesisLiveEvaluation({env:fixture.env,sealDependencies:{...fixture.deps,runGit:gitFake(fixture.head,{ignored:false})},makeVerifier})).rejects.toThrow(/NOT_IGNORED/);expect(makeVerifier).not.toHaveBeenCalled()});
  it("accepts only a canonical ignored clean contract through preflight",async()=>{const fixture=await sealedFixture();fixture.contract.git_sha=fixture.head;await writeFile(fixture.file,JSON.stringify(fixture.contract));await expect(validateFinalSynthesisRunContract(fixture.env,fixture.deps)).resolves.toMatchObject({apiKey:"not-used",contract:{candidate_model:"frozen-model"}})});
});

function gitFake(head:string,options:{dirty?:boolean;tracked?:boolean;ignored?:boolean}={}){return(args:readonly string[])=>{const command=args[0];if(command==="status")return{status:0,stdout:options.dirty?" M tooling/final-synthesis-eval.mts\n":""};if(command==="ls-files")return{status:0,stdout:options.tracked?"artifacts/eval/final-synthesis/run-contracts/contract.json\n":""};if(command==="check-ignore")return{status:options.ignored===false?1:0,stdout:""};if(command==="rev-parse")return{status:0,stdout:`${head}\n`};return{status:1,stdout:""}}}
async function sealedFixture(){const suite=await loadFinalSynthesisDevelopmentSuite();const repo=path.join(tmpdir(),`rediscovery-sealed-${Date.now()}-${Math.random().toString(16).slice(2)}`);const root=path.join(repo,"artifacts","eval","final-synthesis","run-contracts");await mkdir(root,{recursive:true});const head="1".repeat(40);const contract={schema_version:1,git_sha:"0".repeat(40),dataset_version:suite.manifest.dataset_version,corpus_sha256:suite.corpusHash,prompt_version:FINAL_SYNTHESIS_PROMPT_VERSION,prompt_sha256:suite.promptHash,proof_contract_version:FINAL_SYNTHESIS_PROOF_CONTRACT_VERSION,evaluator_version:suite.manifest.evaluator_version,content_slug:"conway-law",content_version:5,content_sha256:suite.contentHash,candidate_model:"frozen-model"};const file=path.join(root,"contract.json");await writeFile(file,JSON.stringify(contract));const deps:FinalSynthesisRunSealDependencies={repoRoot:repo,runGit:gitFake(head)};const env={FINAL_SYNTHESIS_LIVE_RUN:"1",FINAL_SYNTHESIS_RUN_CONTRACT:file,FINAL_SYNTHESIS_MODEL:"frozen-model",OPENAI_API_KEY:"not-used"};return{repo,root,file,head,contract,deps,env}}

function perfectRows(cases:Awaited<ReturnType<typeof loadFinalSynthesisDevelopmentSuite>>["cases"],nodes:Awaited<ReturnType<typeof loadFinalSynthesisDevelopmentSuite>>["requiredNodes"]):EvaluatedCase[]{return cases.map(item=>{const expectedNodes=Object.fromEntries(nodes.map((node:{nodeId:string;requiredComponents:readonly {componentId:string}[]})=>[node.nodeId,node.requiredComponents.every((component:{componentId:string})=>item.expected_components[component.componentId])]));return{caseId:item.id,expectedEligible:item.expected_eligible,predictedEligible:item.expected_eligible,expectedNodes,predictedNodes:expectedNodes,expectedComponents:item.expected_components,predictedComponents:item.expected_components,regressionExact:true,schemaApplicationValid:true,unavailable:false,retried:false,attempts:[{latencyMs:10}]}})}
