import { createHash } from "node:crypto";
import { readFile, readdir } from "node:fs/promises";
import path from "node:path";
import postgres from "postgres";
import { approvedContentSchema } from "../src/domain/content/schema.ts";

const approvedDirectory=path.resolve("content/approved");
const canonical=(value:unknown):string=>Array.isArray(value)?`[${value.map(canonical).join(",")}]`:value&&typeof value==="object"?`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${canonical(v)}`).join(",")}}`:JSON.stringify(value);
async function files(){return (await readdir(approvedDirectory)).filter(f=>f.endsWith(".json")).sort();}
async function validated(){return Promise.all((await files()).map(async file=>({file,content:approvedContentSchema.parse(JSON.parse(await readFile(path.join(approvedDirectory,file),"utf8")))})));}
async function migrate(databaseUrl:string){const sql=postgres(databaseUrl,{max:1});try{await sql`CREATE TABLE IF NOT EXISTS schema_migrations(name text PRIMARY KEY,applied_at timestamptz NOT NULL DEFAULT now())`;const directory=path.resolve("supabase/migrations");for(const name of (await readdir(directory)).filter(f=>f.endsWith(".sql")).sort()){const [seen]=await sql<{name:string}[]>`SELECT name FROM schema_migrations WHERE name=${name}`;if(seen)continue;const body=await readFile(path.join(directory,name),"utf8");await sql.begin(async tx=>{await tx.unsafe(body);await tx`INSERT INTO schema_migrations(name) VALUES(${name})`;});console.log(`migrated ${name}`);}}finally{await sql.end();}}
async function seed(databaseUrl:string){const sql=postgres(databaseUrl,{max:1});try{for(const {file,content} of await validated()){const hash=createHash("sha256").update(canonical(content)).digest("hex");await sql.begin(async tx=>{const [item]=await tx<{id:string}[]>`INSERT INTO content_items(slug) VALUES(${content.slug}) ON CONFLICT(slug) DO UPDATE SET slug=EXCLUDED.slug RETURNING id`;const [existing]=await tx<{id:string;content_hash:string}[]>`SELECT id,content_hash FROM content_versions WHERE content_item_id=${item!.id} AND version=${content.version}`;if(existing&&existing.content_hash!==hash)throw new Error(`${file}: approved version differs; create a new version`);const version=existing??(await tx<{id:string}[]>`INSERT INTO content_versions(content_item_id,version,schema_version,content_hash,status,public_play,judge_rubric,server_policy,reveal_content,approved_at) VALUES(${item!.id},${content.version},${content.schema_version},${hash},'APPROVED',${tx.json(content.PUBLIC_PLAY)},${tx.json(content.JUDGE_RUBRIC)},${tx.json(content.SERVER_POLICY)},${tx.json(content.REVEAL_CONTENT)},${content.approved_at}) RETURNING id`)[0]!;for(const day of content.schedule)await tx`INSERT INTO daily_schedule(canonical_date,sequence_number,release_at,content_version_id) VALUES(${day.canonical_date},${day.sequence_number},${day.release_at},${version.id}) ON CONFLICT(canonical_date) DO UPDATE SET sequence_number=EXCLUDED.sequence_number,release_at=EXCLUDED.release_at,content_version_id=EXCLUDED.content_version_id WHERE daily_schedule.content_version_id=EXCLUDED.content_version_id`;});console.log(`seeded ${file} ${hash}`);}}finally{await sql.end();}}
const command=process.argv[2];const url=process.env.DATABASE_URL??"postgresql://postgres:postgres@127.0.0.1:54322/postgres";
if(command==="validate"){for(const {file} of await validated())console.log(`valid ${file}`);}else if(command==="migrate")await migrate(url);else if(command==="seed")await seed(url);else throw new Error("Expected validate, migrate, or seed");
